version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node-18:
    docker:
      - image: cimg/node:18.4
      - image: cimg/node:17.9

jobs:
  build_and_test:
    executor: 
      name: node-18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - run:
          command: yarn test
          name: Run tests

workflows:
  main:
    jobs:
      - build_and_test
