version: 2.1

executors:
  docker:
    resource_class: small
    docker:
      - image: cimg/base:current
  macos:
    resource_class: small
    macos:
      xcode: 11.4

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          node-install-dir: /usr/local
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
          with-cache: true
          cache-version: v2
      - run:
          command: yarn build
          name: Build app
      - run:
          command: yarn test-ci
          name: Run tests
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: ./reports/junit
          destination: reports

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              os: [docker]
              node-version:
                [
                  '18',
                  '17',
                  '16',
                  '15',
                  '14',
                  '13',
                  '12',
                  '11',
                  '10',
                  '9',
                  '8',
                  '7',
                  '6',
                  '5',
                  '4',
                  '3',
                  '2',
                  '1',
                  '0.12',
                  '0.11',
                  '0.10',
                  '0.9',
                  '0.8',
                  '0.7',
                  '0.6',
                  '0.5',
                  '0.4',
                  '0.3',
                  '0.2',
                  '0.1',
                ]
