version: 2.1

executors:
  docker:
    docker:
      - image: cimg/base:current
  macos:
    macos:
      xcode: 11.4

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          node-install-dir: /usr/local
          install-yarn: true
      - node/install-packages:
          pkg-manager: yarn
          with-cache: false
      - run:
          command: yarn build
          name: Build app
      - run:
          command: whereis yarn; sudo whereis yarn;
      - run:
          command: sudo -E yarn test-ci
          name: Run tests
      - store_test_results:
          path: ./reports/junit

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              os: [docker]
              node-version: ["18.4.0"]